import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import NewsFeed from "@/components/Utility/NewsFeed";
import NewsAdsBanners from "@/components/Home/NewsAdsBanners";
import TopStoriesArea from "@/components/Home/TopStoriesArea";
import VideoArea from "@/components/Home/VideoArea";
import MoreNews from "@/components/Home/MoreNews";
import LatestedBottomNews from "@/components/Home/LatestedBottomNews";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NewsFeed />
      <NewsAdsBanners />
      <TopStoriesArea />
      <VideoArea />
      <MoreNews/>
      <LatestedBottomNews/>
    </>
  );
}
